---
- name: SaaS Deployment
  hosts: local
  become: yes
  vars:
    app_name: "{{ app_name }}"
    repo_url: "{{ repo_url }}"
    branch: "{{ branch }}"

  tasks:
    - name: Debug - Print Variables
      debug:
        msg:
          - "App Name: {{ app_name }}"
          - "Repo URL: {{ repo_url }}"
          - "Branch: {{ branch }}"

    - name: Ensure repository directory exists
      file:
        path: "/var/www/{{ app_name }}"
        state: directory
        mode: "0755"

    - name: Check if directory is a valid Git repository
      stat:
        path: "/var/www/{{ app_name }}/.git"
      register: git_status

    - name: Debug - Print Git Repo Status
      debug:
        msg: "Git Repo Exists: {{ git_status.stat.exists }}"

    - name: Clone the repository if it is not a Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "/var/www/{{ app_name }}"
        version: "{{ branch }}"
        force: yes
      when: not git_status.stat.exists

    - name: Pull latest changes if repository already exists
      command: git pull origin "{{ branch }}"
      args:
        chdir: "/var/www/{{ app_name }}"
      when: git_status.stat.exists

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: "/var/www/{{ app_name }}"

    - name: Build the project
      command: npm run build
      args:
        chdir: "/var/www/{{ app_name }}"

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
