---
- name: SaaS Deployment
  hosts: vps
  become: yes
  vars:
    app_name: "{{ app_name }}"
    repo_url: "{{ repo_url }}"
    branch: "{{ branch }}"

  tasks:
    - name: Ensure repository is updated
      git:
        repo: "{{ repo_url }}"
        dest: "/var/www/{{ app_name }}"
        version: "{{ branch }}"
        force: yes

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: "/var/www/{{ app_name }}"

    - name: Build the project
      command: npm run build
      args:
        chdir: "/var/www/{{ app_name }}"

    - name: Copy built files to Nginx directory
      command: cp -r /var/www/{{ app_name }}/build/* /var/www/test

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
