---
- name: SaaS Deployment
  hosts: local
  become: yes
  vars:
    app_name: "{{ app_name }}"
    repo_url: "{{ repo_url }}"
    branch: "{{ branch }}"

  tasks:
    - name: Ensure repository exists
      stat:
        path: "/var/www/{{ app_name }}"
      register: repo_status

    - name: Clone the repository if it does not exist
      git:
        repo: "{{ repo_url }}"
        dest: "/var/www/{{ app_name }}"
        version: "{{ branch }}"
        force: yes
      when: not repo_status.stat.exists

    - name: Pull latest changes if repository already exists
      command: git pull origin "{{ branch }}"
      args:
        chdir: "/var/www/{{ app_name }}"
      when: repo_status.stat.exists

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: "/var/www/{{ app_name }}"

    - name: Build the project
      command: npm run build
      args:
        chdir: "/var/www/{{ app_name }}"

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
