name: Deploy to Frontend App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure target directory exists on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "${{ secrets.VPS_SSH_KEY }}"
          script: |
            mkdir -p ~/ansible-playbook/${{ github.repository }}

      - name: Copy `.ansible/` directory to VPS using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "${{ secrets.VPS_SSH_KEY }}"
          source: ".ansible"
          target: "~/ansible-playbook/${{ github.repository }}"
          overwrite: true

      - name: Run Ansible Playbook on VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "${{ secrets.VPS_SSH_KEY }}"
          script: |
            cd ~/ansible-playbook/${{ github.repository }}
            ansible-playbook -i inventory.ini deploy.yml \
              --extra-vars "app_name=test \
                            repo_url=git@github.com:${{ github.repository }}.git \
                            branch=${{ github.ref_name }}"
