name: Deploy to VPS

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Secret Variables (Masked)
        run: |
          echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
          echo "VPS_USER: ${{ secrets.VPS_USER }}"
          echo "VPS_SSH_KEY: [MASKED]"  # Avoid printing the private key

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "${{ secrets.VPS_SSH_KEY }}"
          key_path: "./private_key"
          script: |
            echo "✅ Successfully connected to VPS"
            uname -a
