name: Deploy React Vite Project to VPS

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Configure SSH and Test Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_PASSWORD }}" > ~/.ssh/password
        chmod 600 ~/.ssh/password
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        # Test SSH connection with password authentication
        sshpass -f ~/.ssh/password ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'Connection successful'"
