name: Deploy to VPS

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Secret Variables (Masked)
        run: |
          echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
          echo "VPS_USER: ${{ secrets.VPS_USER }}"
          echo "VPS_SSH_KEY: [MASKED]"  # Avoid printing the private key

      - name: Test SSH Connection
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: "uname -a"
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          privateKey: ${{ secrets.VPS_SSH_KEY }}
