name: "Run Nmap Scan"

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      target:
        description: "The domain or IP address to scan with Nmap"
        required: true

permissions:
  contents: read
  issues: write # ✅ Required for issue creation

jobs:
  nmap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nmap
        run: sudo apt-get update && sudo apt-get install -y nmap

      - name: Run Nmap Scan
        uses: marcuwynu23/nmap-action@v1.0.0
        with:
          target: "${{ github.event.inputs.target }}"
          issue_title: "🚨 Nmap Security Scan Alert"
          fail_action: "true"
          allow_issue_writing: "true"
