name: Setup Deployment

on:
  workflow_dispatch: # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure target directory exists on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "${{ secrets.VPS_SSH_KEY }}"
          script: |
            if [ ! -d "~/projects/${{ github.repository }}" ]; then
              mkdir -p ~/projects/${{ github.repository }}
            fi

      - name: Copy `.ansible/` directory to VPS using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "${{ secrets.VPS_SSH_KEY }}"
          source: ".ansible/." # Copies only the contents, not the folder itself
          target: "~/projects/${{ github.repository }}"
          overwrite: true

      - name: Run Ansible Playbook on VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "${{ secrets.VPS_SSH_KEY }}"
          script: |
            cd ~/projects/${{ github.repository }}
            ansible-playbook -i .ansible/inventory.ini .ansible/setup.yml \
              --extra-vars "app_name=test \
                            domain_name=${{ vars.DOMAIN_NAME }} \
                            repo_url=git@github.com:${{ github.repository }}.git \
                            branch=${{ github.ref_name }} \
                            repositoryDirectory=${{ github.repository }}"
